---
title: "First Knit"
author: "Jashaun Smith"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### I attended Paramount High School in 2017. I graduated in the month of June. Math is way more easier than English because i like numbers. My favorite subject in High School was math.    
  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

###   
  At home I use a windows computer. I rate myself at solid 6 to 7 at knowing how to use the computer. Yes I have internet access at home.
   

## Others and You?   
 What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

###    
I am ok with being called my government name, which is Jashaun Smith.  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

###     
 I want to have a career in X-ray technician because there will always be jobs in the nursing field. Thed college subject that best interest me is numerous like Math and English. 
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

###      
  I have never been out of the country, But if i ever get the chance I would love to go visit Hawaii. If i got drafted to the military I would choose to go into the Marines because my Grandfather was a Marine.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

###   
I am taking Math 115 because it is a requirement before I can be able to go into my program. The grade that i need is a passing grade but I am aiming for an A. My plan is to graduate with a AA and go purse the career that I choose.
   
 






  




